### ISSUE TITLE
Rules seem to only save up to two separate items at a time

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#133]
Steps:
1) Log into Omni
2) Go to Fridge
3) Chang the temperate threshold for Y-Hata, then the other two individual devices
4) Check back on the tempterate threshold for Y-Hata again

Occurs:
The rules for Y-Hata are set back to the defaults, claiming that no rules where ever put into place.
![getting rules error](https://cloud.githubusercontent.com/assets/12438510/7873725/e4dbb7d2-055a-11e5-87e8-a024577aa539.png)

**Comment by patrickomni** [comment]
this should be fixed.

**Comment by CaseyDengler** [comment]
It's fixed on the site level, however individual devices still get set back to their defaults.

**Comment by patrickomni** [comment]
this might be a dupe of one already on chris

**Comment by christopherdude** [comment]
I'm not seeing this occur in dev.  Perhaps already fixed by SQL stuff?

**Comment by davroth** [comment]
Related to #110 ; fix in V1

**Comment by davroth** [comment]
There still appears to be a problem w/ rules on new site using IE 11 and Win 8.1:
1. Click Test Fridge
2. Check rule at "global" level, observe Patrick Fridge set to receive alerts
3. Click Fridge 1, observe Patrick Fridge shown as receiving alerts, click Test Fridge to receive alerts too
4. Click rule at "global" level again

Expected: global rule only shows Patrick Fridge

Actual: Test Fridge also set to receive alerts

**Comment by davroth** [comment]
Behavior has changed, but still can only save 1 rule
1. Click Test Fridge
2. Check rule at "global" level, observe no rules set
3. Select Patrick Fridge to receive alerts, click save rule, see success bubble
4. Click Fridge 2, notified no rules exist
5. Select Test Fridge to receive alerts, click save rule, see success bubble
6. Click rule at "global" level

Expected: see old rule w/ Patrick Fridge shown as receiving alerts

Actual: notified no rules set

**Comment by davroth** [comment]
Behavior has changed, but rules still not right - could be a dirty buffer (see steps below) 
1. Click Test Fridge
   1. Check rule at "global" level, observe Patrick Frdige is receiving alerts, click cancel
2. Select Fridge, see Test Fridge and Patrick Frdige are receiving alerts
3. Un select Patrick Frdige, click save, see success bubble
   5.Check rule at "global" level, observe both Test Fridge and Patrick Frdige are set to receive alerts
4. Check rule for Fridge 1, observe no rules found, click cancel
5. Check rule at "global" level again, observe only Patrick Frdige is receiving alerts

Chrome v43, Windows 8.1

**Comment by patrickomni** [comment]
I think this is by design, though the design may not be right.  Let's review

**Comment by patrickomni** [comment]
I didn't understand this before.  This is fixed now

**Comment by davroth** [comment]
1. Browse to https://omnim2m.net, log in as Patrick, select Test Fridge
2. Click "global" rules; observe that Patrick Frdige is set to receive alerts; click cancel
3. Click Fridge 1; clear notification that no rules are set; select Test Fridge to receive alerts, save rule, and observe success bubble
   4.Select "global" rules

Expected - Patrick Frdige set to receive alerts

Actual - getting rules for this item returned no results

Same results on IE 11 and Chrome 43

**Comment by christopherdude** [comment]
Fixed

**Comment by davroth** [comment]
able to save rules at global and device level w/o interference
