### ISSUE TITLE
Active Alerts grid - doesn't return results after device scope filter changed two times

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#241]
1.  Browse to https://nettelpong.azurewebsites.net/sv, chrome 43, windows 8.1, login as dave, select Sempra
2. observe landing page (No data available msg in Active Alerts grid)
3. change device scope filter to station 8; observe landing page (No data available msg in Active Alerts grid)
4. change device scope filter to station 2; observe landing page

Expected - Active Alerts grid displays No data available msg

Actual - Active Alerts grid never returns control (little wheel keeps spinning)

That condition continues to occur until I return to main account impersonation page and then re-enter Sempra. Upon entry, I see the "no data" msg. If I filter to Station 2, I see a new "no data" msg. But when I filter to station 8, the wheel returns and keeps spinning

**Comment by peters95** [comment]
Starting to work on this now.

**Comment by davroth** [comment]
Active Alerts grid now not returning any results upon initial entry
![capture - sempra no results](https://cloud.githubusercontent.com/assets/12534533/8790760/79b84508-2f06-11e5-8c05-6db6b7415a6c.PNG)

**Comment by patrickomni** [comment]
This was fixed last night and i cannot repro anymore

**Comment by davroth** [comment]
Still seeing this for Tank, Fridge, and Traps on both IE and FireFox. Below is picture of Sempra 1 minute after landing page starts to display
![capture - active alertspng](https://cloud.githubusercontent.com/assets/12534533/8814708/aa09bbb0-2fc4-11e5-9983-bf783da43cc4.PNG)

**Comment by davroth** [comment]
Reported by Frank to be recurring on Chrome - does not repro w/ IE or FireFox

**Comment by christopherdude** [comment]
I believe I've fixed this now.  It was actually refreshing the grid multiple times due to an incorrect js call from C#.  Now I just loadpage() method in C# to the JS
