### ISSUE TITLE
Norm's - Please wait... dialog doesn't go away after selecting Fridge Devices

### ISSUE THREAD

**Issue by davroth** [patrickomni/omnimobileserver#296]
Introduced w/ #294 
1. Browse to https://omnim2m.net, chrome v43, windows 8.1, login as dave, select Norm's
2. Set device filter to Fridge Devices

Expected - screen to refresh w/ only fridge devices

Actual - please wait dialog appears and does not go away; refreshing screen brings back the "all" view

Note - the expected results happen when selecting freezer and all other devices

![capture - fridge devices](https://cloud.githubusercontent.com/assets/12534533/9484207/18cdb506-4b5e-11e5-804b-b5456efe6538.PNG)

**Comment by christopherdude** [comment]
THis is fixed with changeset 865 from 7/23/2015

**Comment by davroth** [comment]
Problem still repro's w/ following steps after going to Norm's Landing Page:
1. Select Freezers and page loads properly
2. Select Other devices and page loads properly
3. Select Fridges and page loads properly
4. Select All (global)

Expected: page loads properly

Actual: "please wait" sticks around

Google built developer tools into Chrome (right click anywhere on page and select "Inspect Element" - the last choice. then click red "x" at top of pane that comes up. this will bring up a console view where errors are displayed. See picture below for the error
#292 

![capture - please wait error](https://cloud.githubusercontent.com/assets/12534533/9552151/b8a5d492-4d6a-11e5-8e08-454744537394.PNG)

**Comment by davroth** [comment]
John believes the error is in an Msft Ajax library and may be corrected by changing to a more google-friendly library
