### ISSUE TITLE
Y-Hata and Boat #2 seem to stick with (74F to 92F) after changing their slider rules a number of times

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#36]
Steps to reproduce:
1) Log into Omni
2) Impersonate Fridge
3) Make and save frequent changes in Boat #2 and Y-Hata
4) Observe changes made

Expected:
The last rules made for each section should change the sliders after examining the rules again.

Occurs:
No matter what temperatures are given, Y-Hata and Boat #2 refuse to change their numbers form (74F to 92F).

Note:
This bug came up after I made a ton of changes to the rules for both Boat 2 and Y-Hata trying to reproduce a bug from issue #32. This bug occurred in both Chrome and IE.

**Comment by patrickomni** [comment]
The fix that Chris put in ("There are no rules so we are defaulting") wasn't quite right.   We have to look at all result sets from all tables.   It should always return at least one row.

Get 616 before finalizing fix

**Comment by patrickomni** [comment]
Check for DeviceId = -1, if so then pop the "default rules have been assigned" thingee

**Comment by christopherdude** [comment]
I have fixed this to check for DeviceId = -1.  Please verify that it works.

**Comment by CaseyDengler** [comment]
The slider is still not behaving right. Y-Hata now refuses to move from (-22F to 30F), Boat 1 works fine, Boat 2 is a bit odd. For Boat 2, I was able to save the first change made, moving the temperature cap to (-22F to 143F), but it's stuck at that. Any attempts to save new changes are ignored, aside from a pop up saying that the rules have been saved.

The individual units for Boat 2 act the same as Y-Hata, (staying at -22F to 30F) and refuse to change. However, every time the rules are opened for these units, a pop up says "Getting rules for this item returned no results. We have set some suggested values for you, but they will not be implemented unless you click the save rule button."
![getting rules box](https://cloud.githubusercontent.com/assets/12438510/7712206/aeb7d3ee-fe24-11e4-869a-e10276ce9d52.png)

**Comment by christopherdude** [comment]
He's right - this is the same error where rules aren't saving.  Line 174 of ModalRulesSettings.ascx.cs is where it gets saved, but I need a visual check on proper params being passed.

**Comment by patrickomni** [comment]
Fixed

**Comment by CaseyDengler** [comment]
Not able to change the temperatures from (-22F to 30F).

Note: No pop up saying that rules have been saved, and only works on the site level. Individual devices are fine.

**Comment by patrickomni** [comment]
This at the site level

**Comment by patrickomni** [comment]
Fixed
