### ISSUE TITLE
Fridge Device Details graph shows incorrect data for about a second when turning off and on other devices

### ISSUE THREAD

**Issue by CaseyDengler** [patrickomni/omnimobileserver#43]
Steps:
1) Log into Omni
2) Go to Fridge
3) Deselect Fridge 2 (right now only device with data, not sure if bug)
4) Deselect either Fridge 1 or Demo Device

Expected:
No data is shown on the graph.

Occurs:
For a moment, the data for Fridge 2 (which is to be disabled) shows up on the graph before it becoming blank.
![tank graph momentary error](https://cloud.githubusercontent.com/assets/12438510/7714256/18b3d808-fe32-11e4-9f57-6c04730d2b85.png)

**Comment by patrickomni** [comment]
This was a problem with too much data getting pumped in.  Should be fixed now.

**Comment by CaseyDengler** [comment]
I'm unfortunately still able to reproduce the error.
![tank graph error again](https://cloud.githubusercontent.com/assets/12438510/7753489/9fe49ae2-ff9a-11e4-9ea0-78676ab80d52.png)

**Comment by CaseyDengler** [comment]
Just realized that I said the issue was in Tanks when it was actually in Fridge. Fixed it up now.

**Comment by DaveRoth** [comment]
STOP THIS FEED / REMOVE MY EMAIL

Dave Roth

**Comment by CaseyDengler** [comment]
I'm terrible with communication. The issue itself is not fixed yet, just my inconsistency with Tank/Fridge in the original posting. Still visible in Fridge.

**Comment by patrickomni** [comment]
Fixed

**Comment by CaseyDengler** [comment]
Not fixed yet. One more miss and you owe me donuts?

![still with graph](https://cloud.githubusercontent.com/assets/12438510/7780057/3ab51e08-008f-11e5-95df-53ad1e2644ee.png)

**Comment by davroth** [comment]
Using IE 11 and Windows 8.1, I see all results expected:
- 2 lines on graph when 2 of 2 devices are selected; 
- 1 line on graph when 1 of 2 devices are selected
- "no data to display" when 0 of 2 devices are selected

It is true that when switching from 0 devices selected to 1 device selected - the system briefly displays a line graph that is quickly erased/replaced by the correct graph. The briefly displayed graph appears to result from an uncleared buffer. For me, this remaining issue is annoyance level, so i'm going to close the bug.
