### ISSUE TITLE
On traps, carousel still has navigation pointers and shouldn't

### ISSUE THREAD

**Issue by patrickomni** [patrickomni/omnimobileserver#86]

**Comment by patrickomni** [comment]
Fixed

**Comment by davroth** [comment]
This is still a problem - but i think we can defer this to next iteration
1. Browse to site using IE 11 on Windows 8.1 & select Sempra to impersonate
2. view landing page w/ map and arrow controls on carousel
3. Click arrow controls, left, then right

Expected: pane scrolls w/ message saying "no data" OR arrow controls disabled

Actual: arrow controls shown as hyperlinks but nothing happens

**Comment by davroth** [comment]
no repro
